name: Deploy
on:
  push:
    branches: ["master"]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Clone theme repo
        uses: actions/checkout@v4
        with:
          repository: cngei/kc-theme
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: main
          path: theme
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '21'
      - name: Build theme
        run: |
           cd theme
           npm install
           npm run build-keycloak-theme
           mv ./dist_keycloak/keycloak-theme-for-kc-all-other-versions.jar ../theme.jar
           cd ..
      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          file: ./Dockerfile
          push: true
          tags: ${{ github.sha }}
#  deploy:
#    runs-on: ubuntu-latest
#    permissions: write-all
#    steps:
#      - name: Checkout GitOps repo
#        uses: actions/checkout@v4
#        with:
#          repository: cngei/gitops
#          token: ${{ secrets.GITOPS_PUSH_SECRET }}
#          ref: master
#          path: gitops-repo
#          fetch-depth: 0
#      - name: Update ArgoCD config and push
#        run : |
#          cd gitops-repo/keycloak
#          sed -i "s|^\([[:space:]]*image: \).*|\1ghcr.io/cngei/assemblee-cngei:${{ github.sha }}|" deployment.yaml
#          num_files_updated=$(git diff --numstat | wc -l)
#          echo "::notice::${num_files_updated} files were updated"
#          if (( num_files_updated > 0 )); then
#            git config user.name "GitHub Action"
#            git config user.email "servizi.informatici@cngei.it"
#            git add .
#            git commit -m "Action triggered: Updated assemblee to ${{ github.sha }}"
#            git push
#          fi